package Vistas;

/**
 *
 * @author RAUL EDUARDO GOMEZ
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MapaInteractivo
     */
    public frmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Boton_Ajustes = new javax.swing.JButton();
        Boton_TusSalones = new javax.swing.JButton();
        Boton_PuntosDeInteres = new javax.swing.JButton();
        Label_LogoITSON = new javax.swing.JLabel();
        Label_Mapa = new javax.swing.JLabel();
        Label_TextoBusqueda = new javax.swing.JLabel();
        CuadroBusqueda = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Boton_Ajustes.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        Boton_Ajustes.setText("---");
        Boton_Ajustes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_AjustesActionPerformed(evt);
            }
        });
        jPanel1.add(Boton_Ajustes, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 50, 20));

        Boton_TusSalones.setBackground(new java.awt.Color(231, 231, 231));
        Boton_TusSalones.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        Boton_TusSalones.setForeground(new java.awt.Color(25, 111, 196));
        Boton_TusSalones.setText("Tus salones");
        jPanel1.add(Boton_TusSalones, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, 120, -1));

        Boton_PuntosDeInteres.setBackground(new java.awt.Color(231, 231, 231));
        Boton_PuntosDeInteres.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        Boton_PuntosDeInteres.setForeground(new java.awt.Color(25, 111, 196));
        Boton_PuntosDeInteres.setText("Puntos De Interes");
        jPanel1.add(Boton_PuntosDeInteres, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 140, -1));

        Label_LogoITSON.setIcon(new javax.swing.ImageIcon("C:\\Users\\molin\\OneDrive\\Documentos\\Mapa Interactivo\\Proyecto-Mapa-Interactivo\\src\\main\\java\\Utilerias\\Logo_ITSON (1).png")); // NOI18N
        jPanel1.add(Label_LogoITSON, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 250, 80));

        Label_Mapa.setIcon(new javax.swing.ImageIcon("C:\\Users\\molin\\OneDrive\\Documentos\\Mapa Interactivo\\Proyecto-Mapa-Interactivo\\src\\main\\java\\Utilerias\\mapa-itson (1).png")); // NOI18N
        jPanel1.add(Label_Mapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 280, 330));

        Label_TextoBusqueda.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Label_TextoBusqueda.setText("Búsqueda:");
        jPanel1.add(Label_TextoBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 40));

        CuadroBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuadroBusquedaActionPerformed(evt);
            }
        });
        jPanel1.add(CuadroBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 190, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CuadroBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuadroBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CuadroBusquedaActionPerformed

    private void Boton_AjustesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_AjustesActionPerformed
        // TODO add your handling code here:
        frmAjustes ajustes = new frmAjustes();
        ajustes.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Boton_AjustesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Ajustes;
    private javax.swing.JButton Boton_PuntosDeInteres;
    private javax.swing.JButton Boton_TusSalones;
    private javax.swing.JTextField CuadroBusqueda;
    private javax.swing.JLabel Label_LogoITSON;
    private javax.swing.JLabel Label_Mapa;
    private javax.swing.JLabel Label_TextoBusqueda;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
